plugins {
    id("gradlebuild.distribution.api-java")
    id("gradlebuild.publish-public-libraries")
}

description = "Tools for hashing files and other content"

dependencies {
    api(projects.stdlibJavaExtensions)

    api(libs.jspecify)

    implementation(libs.guava)
    implementation(libs.hash4j)
}

gradleModule {
    computedRuntimes {
        // Auto-generated by `:checkTargetRuntimes --fix`
        client = true
        daemon = true
        worker = true
    }
}

errorprone {
    nullawayEnabled = true
}
